name: Auto Merge PR

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Auto-approve the pull request
      - name: Auto-approve PR
        id: auto_approve
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: ${{ secrets.prmerge }}

      # Debug: Check auto-approve result
      - name: Print auto-approve result
        run: echo "Auto-approve step outcome: ${{ steps.auto_approve.outcome }}"

      # Install the GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh -y

      # Debug: Verify GitHub CLI installation
      - name: Check GitHub CLI version
        run: gh --version

      # Merge the pull request
      - name: Merge pull request
        if: ${{ steps.auto_approve.outcome == 'success' }}
        run: gh pr merge ${{ github.event.pull_request.number }} --merge --admin --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.prmerge }}
